name: MiKTeX (Windows)
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install MiKTeX
        run: |
          choco install miktex --no-progress --params "/Set:essential"
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Configure MiKTeX
        run: |
          initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --admin --verbose packages update-package-database
          miktex --admin --verbose packages update
          miktex --verbose packages update
          miktex --admin --verbose packages install cm-super l3kernel l3packages l3build l3experimental l3backend 
          miktex --admin --verbose fndb refresh
          initexmf --admin --verbose --update-fndb
          initexmf --admin --verbose --mklinks --force
          updmap --admin

      - name: Prepare l3build
        run: |
          # Ensure that "kpsewhich --var-value TEXMFHOME" returns something
          initexmf --user-roots="C:/texmf"

      - run: l3build install

      - run: l3build check

      - run: l3build ctan -H --show-log-on-error

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: CTAN
          path: 'build/distrib/ctan/*.zip'
