name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: registry.gitlab.com/islandoftex/images/texlive:latest-small
    #  options: --user root
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
           package_file: tl_packages

      - run: l3build install 

      - run: l3build check

      - run: l3build ctan -H --show-log-on-error

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: CTAN
          path: 'build/distrib/ctan/*.zip'
